//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIZ_Markerspace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public System.Guid machine_id { get; set; }
        public System.Guid room_id { get; set; }
        public string machine_name { get; set; }
        public string room_name { get; set; }
        public int status { get; set; }
        public double service_level { get; set; }
        public double usage_time { get; set; }
        public double total_usage_time { get; set; }
        public int service_flag { get; set; }
        public double current_threshold { get; set; }
        public int role_access { get; set; }
        public int hardware_service_flag { get; set; }
    }
}
